### ISSUE TITLE
Call healthchecks via service not via ingress

### ISSUE THREAD

**Issue by carstenlenz** [AOEpeople/vistecture-dashboard#1]
Currently the healthchecks are called via the ingress of the probed application. That means all traffic goes over the public network. As the dashboard is typically run as internal application as well it should call all the healthchecks via the (internal) service to prevent the roundtripping.

**Comment by bastianccm** [comment]
Initially the healthcheck was a ping to the ingress, to ensure it is setup and routed correctly.
When the dashboard evolved it got more features, and a more specific healthcheck mechanism.

To resolve this issue we should think about supporting both healthchecks.

**Comment by Dbzman** [comment]
Closing this as we support both already.
